### ISSUE TITLE
Collected code samples

### ISSUE THREAD

**Issue by raganwald** [raganwald/javascript-allonge-six#32]
JSFiddles, gists,a  repo, files in the repo, something (anything!) that collects samples into coherent chunks that people can download and use.

**Comment by fugalfunkster** [comment]
FWIW: While I study Allonge, I take notes in emacs' org-mode, which allows me to execute code samples inline. I execute the samples with org-mode's code-blocks, which I set up to transpile with babel, and pipe into a node REPL. The output from node is piped back into my notes. I can even export select samples (recipes) to a .js file, using the tangle feature.  

The tight integration between my notes, the code samples, and the REPL results has really augmented my experience with Allonge.
